apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: wolf_client-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: wolf_client
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
