apiVersion: v1
kind: Service
metadata:
  name: wolf-client
  annotations:
    cloud.google.com/backend-config: '{"ports": {"80":"wolf-client-backend-config"}}'
    cloud.google.com/neg: '{"ingress": true}'
  labels:
    service: wolf-client
spec:
  selector:
    app: wolf-client
  ports:
    - port: 80
